#!/bin/bash


if [ "$(pkexec docker ps | grep efabless_container)" ]; then
	if [ "$( zenity  --question --text="Efabless Container is already running, do you wish to restart it?")" ]; then
		export DESIGNS=$CHSN_PATH
		pkexec docker stop efabless_container
		pkexec docker rm efabless_container
		pkexec docker run -it -d --name efabless_container -p 5901:5901 --user $(id -u):$(id -g) -v $DESIGNS:/foss/designs -e VNC_PW=adamlab12 -e VNC_RESOLUTION=1920x1080 	efabless/foss-asic-tools:beta bash
	fi

else
	pkexec rm efabless_container
	export DESIGNS=$CHSN_PATH
	pkexec docker run -it -d --name efabless_container -p 5901:5901 --user $(id -u):$(id -g) -v $DESIGNS:/foss/designs -e VNC_PW=adamlab12 -e VNC_RESOLUTION=1920x1080 	efabless/foss-asic-tools:beta bash

fi

zenity --info --text="Opening vnc connection to container..."
vncviewer 127.0.0.1:5901
