#!/bin/bash

##This is not meant to be permanent but is a dirty way around some errors I was having with the efabless docker image

if [ "$(docker ps | grep efabless_container)" ]; then
	if [ "$( zenity  --question --text="Efabless Container is already running, do you wish to restart it?")" ]; then
		export DESIGNS=CHSN_PATH
		killall -9 docker
		docker stop efabless_container
		docker rm efabless_container
		docker run -it -d --name efabless_container -p 5901:5901 --user $(id -u):$(id -g) -v $DESIGNS:/foss/designs -e VNC_PW=yh288hG5k -e VNC_RESOLUTION=1920x1080 	efabless/foss-asic-tools:beta bash
	fi

else
	docker rm efabless_container
	export DESIGNS=CHSN_PATH
	docker run -it -d --name efabless_container -p 5901:5901 --user $(id -u):$(id -g) -v $DESIGNS:/foss/designs -e VNC_PW=yh288hG5k -e VNC_RESOLUTION=1920x1080 	efabless/foss-asic-tools:beta bash

fi

zenity --info --text="Opening vnc connection to container..."
vncviewer -passwd /home/NAME/.vncpass 127.0.0.1:5901

