#!/bin/bash

git clone -b mpw-7a https://github.com/efabless/caravel_user_project_analog
cd caravel_user_project_analog 

export PDK_ROOT=$1
export PDK=sky130B

make install
make pdk-with-volare
make precheck
